version: '3.8'

services:
  web:
    build: ./app
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static:/home/app/web/static
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:14.3-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  db_backup:
    image: prodrigestivill/postgres-backup-local
    restart: always
    user: postgres:postgres
    volumes:
      - postgres_backup:/var/opt/pgbackups
    links:
      - db:db
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    build: ./nginx
    volumes:
      - static:/home/app/web/static
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  postgres_backup:
  postgres_data:
  static: