version: '3.8'

services:
  web:
    build: ./apps
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static:/home/apps/web/static
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - db

  nginx:
    build: ./nginx
    volumes:
      - static:/home/apps/web/static
    ports:
      - 80:80
    depends_on:
      - web

  db:
    build: ./postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  db_backup:
    image: prodrigestivill/postgres-backup-local
    restart: always
    volumes:
      - postgres_backup:/backups
    links:
      - db:db
    depends_on:
      - db
    env_file:
      - ./.env

volumes:
  postgres_data:
  postgres_backup:
  static:
